###############################################################################
#                          Containers Para DB2                                #
###############################################################################
version: "3.1"
services:
    load-balancer:
      image: nginx:alpine
      container_name: load-balancer
      working_dir: /application
      volumes:
          - ./application/:/application
          - ./resources/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
          - ./resources/nginx/default.conf:/etc/nginx/nginx.conf
      ports:
       #Este debe ser 80:80
       - "8080:80"
      networks:
        sigri-cluster:
            ipv4_address: 172.1.1.2
     
    server-one:
      image: php:7.2-apache
      build:
          context: .
          dockerfile: resources/php/Dockerfile
      container_name: server-one
      working_dir: /var/www/html/
      volumes:
          - ./application/:/var/www/html/
          - ./resources/php/000-default.conf/:/etc/apache2/apache2.conf
      networks:
        sigri-cluster:
            ipv4_address: 172.1.1.3
    
    server-two:
      image: php:7.2-apache
      build:
          context: .
          dockerfile: resources/php/Dockerfile
      container_name: server-two
      working_dir: /var/www/html/
      volumes:
          - ./application/:/var/www/html/
          - ./resources/php/000-default.conf/:/etc/apache2/apache2.conf
      networks:
        sigri-cluster:
            ipv4_address: 172.1.1.4

    server-three:
      image: php:7.2-apache
      build:
          context: .
          dockerfile: resources/php/Dockerfile
      container_name: server-three
      working_dir: /var/www/html/
      volumes:
          - ./application/:/var/www/html/
          - ./resources/php/000-default.conf/:/etc/apache2/apache2.conf
      networks:
        sigri-cluster:
            ipv4_address: 172.1.1.5


networks:
  sigri-cluster:
    driver: bridge
    ipam:
     config:
       - subnet: 172.1.1.0/24
