###############################################################################
#                          Containers Para DB2                                #
###############################################################################
version: "3.1"
services:
    load-balancer:
      image: nginx:alpine
      container_name: load-balancer
      working_dir: /application
      volumes:
          - ./application/:/application
          - ./resources/nginx/proxy.conf:/etc/nginx/conf.d/default.conf
          - ./resources/nginx/default.conf:/etc/nginx/nginx.conf
      ports:
       #O Exponer directamente en el puerto 80
       - "8080:80"
      networks:
        rami-cluster:
            ipv4_address: 172.1.1.2
     
    server-one:
      image: php:5.3-apache
      container_name: server-one
      working_dir: /var/www/html/
      environment:
        - APACHE_RUN_DIR="/var/www/html"
        - APACHE_RUN_USER="www-data"
        - APACHE_RUN_GROUP="www-data"
        - APACHE_LOG_DIR="/var/www/"
      volumes:
          - ./application/:/var/www/html/
          - ./resources/php/000-default.conf/:/etc/apache2/apache2.conf
      networks:
        rami-cluster:
            ipv4_address: 172.1.1.3
    
networks:
  rami-cluster:
    driver: bridge
    ipam:
     config:
       - subnet: 172.1.1.0/24
